### ISSUE TITLE
Code for plotting spectrum of the covariance matrix

### ISSUE THREAD

**Issue by skim0119** [giorgionicoletti/PRR2020_models#1]
Dear @giorgionicoletti,

I recently encountered your research and publication on PRG, and I appreciate the insights you provided. I am currently working through your PRR 2020 paper and attempting to apply the criticality analysis to my own system.

I would like to ensure that my implementation is correct, but I am having some difficulties with plotting the spectrum of the covariance matrix as your plot on the paper. Would it be possible for you to share the code you used in your analysis? I would greatly appreciate your help.

**Comment by giorgionicoletti** [comment]
Hi @skim0119, sorry for the late reply, it's a super busy period. I don't have the original code at hand at the moment, but the plot should be fairly simple to reproduce - something along the line of `np.sort(np.linalg.eigvalsh(covariance))[::-1]` to get the ranked eigenvalues of the covariance matrix `covariance` I can give you more details if needed.

**Comment by skim0119** [comment]
@giorgionicoletti Thank you so much for your response! I think there is a part of the explanation that I am not fully understanding, and I was hoping you could help clarify. In the plot where you show the scaling of eigenvalues for each cluster `K`:
<img width="314" alt="image" src="https://github.com/user-attachments/assets/34f8dc78-c840-4077-b0e5-1a077bc4bbd3">
it looks like the number of eigenvalues remains the same even after the coarse-graining iteration. From my understanding, the coarse-graining step should reduce the size of the covariance matrix, and the number of eigenvalues should also be reduced in half. 

I think there must be some misunderstanding on my end regarding the coarse-graining steps and how to construct the covariance matrix. Could you give a little more implementation details on the coarse-graining steps?

Thank you,

**Comment by giorgionicoletti** [comment]
No problem @skim0119 ! You are right, the number of eigenvalues is reduced in half at each coarse-graining iteration. You can see that from the plot as the spacing of the eigenvalues changes. Since we are plotting them as a function of `r/K`, where `r` is the rank and `K` is the cluster size. Thus, `r/K` is always between 1/K and 1, and indeed you can see on the left of the plot that the first eigenvalue for different colors starts at different values of `r/K`.

I may have some time in the future to upload the actual code for coarse-graining, although it's quite old and poorly documented. I'll see if I can optimize it a bit and make it public. But the basic idea is very simple: compute the covariance matrix; find the largest entry; group together the corresponding variables and remove the entry from the covariance; repeat until no variables are left.

I hope this helps!

**Comment by skim0119** [comment]
I understand now. Thank you for the clarification!
